### ISSUE TITLE
[1.15.2] Issue with Ring of Flight

### ISSUE THREAD

**Issue by realTIMematrix** [Focamacho/RingsOfAscension#1]
Hi,

I recognized something in survival mode:

1. wear ring of flight
2. start flying with double space
3. move ring of flight of or throw away - be still in creative flight
4. only when you get down to bottom and land you will loose the effect.

Is this behaviour really wanted? otherwise this mechanic can provoke players to switch ring and to stack several effects at the same time

btw. nice mod :-)

**Comment by Focamacho** [comment]
Thanks for the report! I'll upload a new version to curseforge now.
