### ISSUE TITLE
Ring of flight not working - fabric 16.1.1

### ISSUE THREAD

**Issue by Darkenwolf2050** [Focamacho/RingsOfAscension#10]
This ring does not grant flight. It has removed all fall damage though. Pressing double space does not allow me to ascend. Removed all other items from inventory and tried on a different accounts character.

Run on a modded server. Flight-allowed is set to true in server properties.

**Comment by Darkenwolf2050** [comment]
That said this is a great mod and you've done excellent work with it. My daughter loves the ring of speed she found.

**Comment by focamacho** [comment]
I'm glad you liked the mod :)
v1.0.4 should fix your issue
Here is: https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/3003569

**Comment by focamacho** [comment]
For some reason the file got stuck in "processing" and I just realized it now.
I submitted a ticket to curseforge to solve the problem.
![image](https://user-images.githubusercontent.com/48870573/88243273-41bf2d80-cc66-11ea-97dc-ae9602913d60.png)

**Comment by Darkenwolf2050** [comment]
Fantastic, was hoping it was something like that. I'll test it out once the file shows on curseforge.

**Comment by focamacho** [comment]
Curseforge finnaly approved the file. https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/3003569

**Comment by Darkenwolf2050** [comment]
Thanks, that's awesome. Just loaded it up and the ring of flying works like
a charm. I have a very excited 6 yr old flying about our base like a crazy
wasp now. She was so excited to find one in a sand temple and so
disheartened when she couldn't fly like Pan (although at least the feather
fall effect saved her when she threw herself off a ravine to test it).

I hope you can continue to create amazing and configurable mods such as
this.
Thanks Again,
Dave.

**Comment by focamacho** [comment]
I'm glad to hear this! :D
Thanks for the bug report and for using my mod!
