### ISSUE TITLE
Ring of Slow Falling not working

### ISSUE THREAD

**Issue by linux-panda** [Focamacho/RingsOfAscension#11]
The ring of slow falling doesn't give the effect visually in the GUI or actually grant the effect at all when equipped, even by itself. Using on a multiplayer server running AOF 3-1.3.1

**Comment by focamacho** [comment]
Hello! The slow falling ring is working fine for me.
However, I tested using it in the modpack all of fabric 3, and it looks like it doesn't really work in the modpack. But not only that, even applying the effect of Slow Falling on me through commands, the effect is applied but does not work.
Probably some mod is interfering with the effect's operation, but I'm pretty sure it's not a bug with Rings of Ascension.
