### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by TheRealJorph** [Focamacho/RingsOfAscension#14]
I left a comment on the main page and was told to leave a message here, but I speak Spanish and would love to help translate the mod into Spanish if you don't already have a translation! Thank you for your wonderful work.
- Jorph

**Comment by focamacho** [comment]
Hello! Here is the file to translate:
[en_us.zip](https://github.com/Focamacho/RingsOfAscension/files/5053918/en_us.zip)

You can send it here after translating it

**Comment by TheRealJorph** [comment]
[es_es.zip](https://github.com/Focamacho/RingsOfAscension/files/5053966/es_es.zip)

Hi there, I took the liberty and started earlier while I waited a reply. Here is the Spanish translation.


  *   Jorph

**Comment by focamacho** [comment]
Thanks!
