### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by drmeystry** [Focamacho/RingsOfAscension#16]
When wearing the fire resistance ring and you end up touching lava the fire effect stays on screen until you quench it, it isn't a big problem its just annoying to have half my screen taken up by pixelated fire.

**Comment by focamacho** [comment]
I can't replicate this bug with only Rings of Ascension, Trinkets and Fabric API installed.
I think this problem is not related to this mod, because all the ring does is give the player the effect of fire resistance.
