### ISSUE TITLE
Rings stop working when you eat, place a block or pick up an item.

### ISSUE THREAD

**Issue by SuruIde** [Focamacho/RingsOfAscension#19]
I don't know if this is an issue with this mod or the trinkets mod, but every time something in your inventory changes, the ring's effect stops working until you remove and replace it in the slot.

**Comment by SuruIde** [comment]
This also happens when you do so much as switch to another slot in your hotbar. The item itself doesn't change location, but it seems that simply being selected is enough to mess with the mod.

**Comment by focamacho** [comment]
I'm pretty sure it is not an issue with Rings of Ascension. It can be an issue with Trinkers or another mod is doing weird things with the effects.
