### ISSUE TITLE
mod not working crashing when u put in the mod

### ISSUE THREAD

**Issue by ninjarayyan21** [Focamacho/RingsOfAscension#20]
whenever i open my minecraft after putting this mod inmy mods folder my mc just doesnt open btw im on tlauncher

**Comment by ninjarayyan21** [comment]
[latest.log](https://github.com/Focamacho/RingsOfAscension/files/6055677/latest.log)

**Comment by focamacho** [comment]
Hello! You log doesn't show any issues with Rings of Ascension, but it have some config-erros with "shulkerboxtooltip" and "automated_crafting".
If it only happens with Rings of Ascension installed, maybe it is a dependency conflict. Try using the latest version of the mod(the beta one): https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/3106016

**Comment by ninjarayyan21** [comment]
ok ill try

**Comment by ninjarayyan21** [comment]
[latest.log](https://github.com/Focamacho/RingsOfAscension/files/6056660/latest.log)
same issue

**Comment by ninjarayyan21** [comment]
is it cause of the other mods?

**Comment by focamacho** [comment]
Hey, do you have Trinkets installed? I can't find it in the log. Trinkets is a dependency for this mod.
https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric

**Comment by ninjarayyan21** [comment]
it is installed

**Comment by focamacho** [comment]
Sorry, i don't know how to help :/
Try running minecraft with only Fabric, Fabric API, Trinkets and Rings of Ascension installed.

**Comment by ninjarayyan21** [comment]
ok ill see. Np btw

**Comment by ninjarayyan21** [comment]
it didnt work I guess just a issue with my pc

**Comment by ninjarayyan21** [comment]
😢 
:(
