### ISSUE TITLE
Ring of Regeneration doesn't actually gain hearts

### ISSUE THREAD

**Issue by chimericdream** [Focamacho/RingsOfAscension#3]
I suspect this is because the rings only apply effects for a second before resetting. Your hearts get the animation from regeneration, but no hearts are actually gained. I eliminated saturation as a factor by granting myself hunger for a short period so that my hunger bar was too low to regain any hearts.

I tested in a bare modpack with the following versions:

Forge: 31.2.0 (1.15.2)
Curios API: 2.0.2.2
Rings of Ascension: 1.3

It would be nice if the rings granted their effects for longer than a second (maybe 30 seconds?), or if the base time was configurable.

**Comment by Focamacho** [comment]
Try changing the config "ringAmplifierRegeneration" from 0 to 1, maybe it can fix the issue.
I'll make some changes to how effects duration works too. Thanks for the report.

**Comment by Focamacho** [comment]
> Try changing the config "ringAmplifierRegeneration" from 0 to 1, maybe it can fix the issue.
NVM, I've found the issue. For some reason minecraft don't regenerates your HP if the effect is applied all the time, I'll fix it in the next version of Rings of Ascension.

**Comment by Focamacho** [comment]
Rings of Ascension 1.4 available on curseforge. Thanks again for the report!
