### ISSUE TITLE
(1.16.1) Issue with Ring of Flight

### ISSUE THREAD

**Issue by JusGman** [Focamacho/RingsOfAscension#5]
Hello i install a mod pack and it has rings of RingsOfAscension in it. 
I found the ring of flight in a chest and noticed a issue with it im not sure if its because of the update or a setting but i cannot fly with it. When i try to activate flight it starts for a second then stops and sort of looks like a double jump

Hope this helps. if needed i could attatch a video :)

**Comment by Focamacho** [comment]
I can't replicate this but I'll make some changes to try fix it.

**Comment by Focamacho** [comment]
Here is https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/2992848

**Comment by JusGman** [comment]
Yeah that fixef the problem thanks :)
