### ISSUE TITLE
Ring of Flight does not work (1.17 Fabric)

### ISSUE THREAD

**Issue by SheriffEllis** [Focamacho/RingsOfAscension#58]
When using the ring of flight (both in singleplayer and multiplayer with flight enabled) creative flight cannot be entered. I have attempted to use the item with my entire inventory empty and nothing changes. When jumping rapidly the fall is slightly slowed in a way that seems like flight is entered and then exited instantly.

Fabric Version: 0.11.6 - 1.17

**Comment by Desempregago** [comment]
to add to this, when trying to fly, you get a log spam regarding Player Ability was updated externally
![image](https://user-images.githubusercontent.com/14002834/127393070-585e8019-75b5-4984-a878-97cec0a8230f.png)

**Comment by focamacho** [comment]
Should be fixed now, thanks for the report!
