### ISSUE TITLE
[main/ERROR]: No GUI provider registered

### ISSUE THREAD

**Issue by ghost** [Focamacho/RingsOfAscension#61]
___
Client: **1.16.5**
API: **36.0**
Trinkets: **2.6.7**
RingOfAscension: **RingsOfAscension-1.16.4-1.1.1**
Modlist & Logs: https://pastebin.com/0j03Z08z

____
#### Issue:
Error after run MC in logs:
No GUI provider registered for field 'final com.focamacho.ringsofascension.config.~

The mod itself works, does this bug have any impact on the gameplay?

___
Regards,
CSS.

**Comment by focamacho** [comment]
It won't affect gameplay at all, but this bug has been fixed in the 1.17 version

**Comment by ghost** [comment]
Thanks for answer, I understand you won't be doing backward compatibility for 1.16.5?

**Comment by focamacho** [comment]
As it's not a game-breaking isue, no
