### ISSUE TITLE
Ring of Flight

### ISSUE THREAD

**Issue by JulianCA1** [Focamacho/RingsOfAscension#65]
When i put the ring on the slot he doesnt do anything.
Last version 1.17.1

**Comment by focamacho** [comment]
Hello, what version are you using?
Forge or Fabric?
Do you have other mods installed?

**Comment by JulianCA1** [comment]
> Hello, what version are you using? 
> Forge or Fabric?
> Do you have other mods installed?

Hey! Im using mod version 1.0.1 on minecraft 1.17.1 FABRIC 
I have mods installed
Ty! for reply

**Comment by Wolfy8198** [comment]
Do you by any chance have the Flight Rings mod installed?

**Comment by focamacho** [comment]
As it is probably another mod causing this bug, i'll close the issue for now.
