### ISSUE TITLE
Rings wont go in trinket slot

### ISSUE THREAD

**Issue by HoodBlah** [Focamacho/RingsOfAscension#66]
I've opened a few worlds to test this out and in all of them I can place the rings in any trinket slots. Shift click doesn't do anything and manually trying to place it wont work either.

**Comment by focamacho** [comment]
Hello, i'm not able to replicate the issue. Can you replicate this with only Trinkets, Rings of Ascension and Fabric API installed?
I think it is a mod incompatibility
