### ISSUE TITLE
How to modify rings slots (Fabric)

### ISSUE THREAD

**Issue by Wolfy8198** [Focamacho/RingsOfAscension#67]
Not an issue, but I was wondering if I could slightly modify the mod in my modpack for my server so that we have three offhand/ring slots instead of one of each hand/ring and offhand/ring slots? I also agree with a previous thread about making the amount of ring slots configurable, with a slight suggestion. Since you can have more than one slot for each kind, according to the page [here](https://github.com/emilyploszaj/trinkets/wiki/Trinkets-Data-Formats) in the Slots section (not sure if I did the link thing right or not ;-;), Maybe you could remove the hand/ring slot? If we have multiple offhand/ring slots, we wouldn't really need it.

**Comment by Wolfy8198** [comment]
I've experimented with the mod a bit, since I'm familiar with using JSON, and I've managed to remove the hand/ring slot, but I don't know how to add the extra offhand/ring slots. I added `"amount": 3,` to the file, but it still doesn't add the extra slots. Don't worry, I won't be distributing the modified version without permission, and only as part of the Genesis Revival modpack when it comes out. A lot of the members of my server have been requesting extra ring slots, so I'm just trying to do this for them. I'm not familiar with mods, not do I have time to learn how to code them right now, what with school, my server, and coding Origins. I understand if you can't add the extra slots/make the amount configurable, so please don't stress yourself trying to do it.

**Comment by Wolfy8198** [comment]
`{
  "replace": false,
  "amount": 3,
  "values": [
    "ringsofascension:ring_fire_resistance",
    "ringsofascension:ring_dolphin",
    "ringsofascension:ring_invisibility",
    "ringsofascension:ring_jump_boost",
    "ringsofascension:ring_luck",
    "ringsofascension:ring_mining",
    "ringsofascension:ring_night_vision",
    "ringsofascension:ring_regeneration",
    "ringsofascension:ring_slow_falling",
    "ringsofascension:ring_speed",
    "ringsofascension:ring_strength",
    "ringsofascension:ring_water_breathing",
    "ringsofascension:ring_slow_resistance",
    "ringsofascension:ring_poison_resistance",
    "ringsofascension:ring_wither",
    "ringsofascension:ring_magnetism",
    "ringsofascension:ring_flight",
    "ringsofascension:ring_hungerless",
    "ringsofascension:ring_experience",
    "ringsofascension:ring_growth",
    "ringsofascension:ring_knockback_resistance",
    "ringsofascension:ring_health",
    "ringsofascension:ring_sponge",
    "ringsofascension:ring_water_walking",
    "ringsofascension:ring_undying"
  ]
}`
This is what I have for the ring.json file, not sure if that's what I needed to do or not, and I can't for the life of me find out what an EAM is, which is what the Trinket wiki mentioned.

**Comment by Wolfy8198** [comment]
Apparently is didn't show the line breaks-

**Comment by focamacho** [comment]
Hello. To be able to modify the amount of slots you'll need a datapack.
I made one as an example for you, it will disable the main hand rings slots and enable three slots for the offhand.

![image](https://user-images.githubusercontent.com/48870573/146418794-0e873b1d-067f-4b0f-9fc0-b2bd4b4edc39.png)

Download:
[MoreRingsSlots.zip](https://github.com/focamacho/RingsOfAscension/files/7729261/MoreRingsSlots.zip)

**Comment by Wolfy8198** [comment]
Huh. I tried a datapack, but it didn't work. I'll have to compare ours to see what I did wrong. Thanks a lot! If I have any issues I'll let you know.
