### ISSUE TITLE
Rings Of Ascention 1.0.2 for MC 1.16.1 Ring of Hungerless

### ISSUE THREAD

**Issue by JillSwift** [Focamacho/RingsOfAscension#7]
Character remains hungerless despite removing the ring from Trinkets offhand ring slot.
Have tried adding it and removing it again, from both main and offhand slots.

(Character does not mind, character is on a diet and the ring is a great help in sticking to it.)

**Comment by focamacho** [comment]
I don't think it's a Rings of Ascension issue, all Ring of Hungerless does is fill your hunger bar every tick and it uses a trinkets method for that.
So if the ring is not ticking as it should, maybe it is a Trinkets' bug.

But I tried it myself and I was unable to replicate the bug

**Comment by JillSwift** [comment]
OKies. I just tried it on a fresh MultiMC instance with just Trinkets and Rings of Ascension installed, and can't replicate it either (and my bad for not trying that before posting an issue).

So. Um. Love the mod!
