### ISSUE TITLE
Ring of flight disappearing

### ISSUE THREAD

**Issue by nillawafers4u** [Focamacho/RingsOfAscension#70]
for some reason the ring of flight is only visible in my inventory when i have clicked on it to move around. at all other times, including when its equip the item is completely invisible. this includes the name of the item and description. it still works as intended but its just a bit strange as all the other rings render fine 

I'm using fabric 0.12.12 by the way

**Comment by nillawafers4u** [comment]
Small update, While continuing to play I've noticed that the ring is completely visible when being throw down in the world, as well as if its in any modded type inventory. (think backpack mods or the iron chests from the iron chest mod) only when its placed in a vanilla inventory does it not seem to render.

**Comment by focamacho** [comment]
I can't replicate this issue.
Make sure you're using the latest version of Trinkets and Rings of Ascension.
I'll be closing this issue for now.
