### ISSUE TITLE
[Feature Request] 1.18.2 Support

### ISSUE THREAD

**Issue by isaaclepes** [Focamacho/RingsOfAscension#74]
Fails to load on MC 1.18.2 / Forge 40.0.32
![image](https://user-images.githubusercontent.com/54421422/160255825-045f0144-ebad-48f1-a117-91dbcce0252e.png)

Crash Report
[crash-2022-03-26_14.20.34-fml.txt](https://github.com/focamacho/RingsOfAscension/files/8356272/crash-2022-03-26_14.20.34-fml.txt)

Latest.log
[latest.log](https://github.com/focamacho/RingsOfAscension/files/8356278/latest.log)

I appreciate your hard work!

**Comment by focamacho** [comment]
Updated to 1.18.2.
https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/3749079
