### ISSUE TITLE
[1.18.2] Internal Server error when using Ring of Growth. (ticking player).

### ISSUE THREAD

**Issue by Gbergz** [Focamacho/RingsOfAscension#75]
Title^

When equipped, you get disconnected with Internal Server error. Server doesn't crash, just throws the player that got it equipped out.
(In the curious menu.)

**Minecraft:** 1.18.2
**Forge:** 40.1.0
**ROA:** 1.0.0 | https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/3749079

**Logs/Crash Info:** https://gist.github.com/Gbergz/1142c2ba9ad2b2b99bebef88d08dcad8

**-** Gbergz

**Comment by focamacho** [comment]
Should be fixed in the latest version. Thanks for the report!
