### ISSUE TITLE
1.19 - Error in Config

### ISSUE THREAD

**Issue by Snaitf** [Focamacho/RingsOfAscension#76]
Rings of Ascension - 1.19 - 1.0

In the location section of the config:

2nd entry says "run" instead of "ruin" for Sponge Ring

ringLocationSponge = "minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small"

**Comment by Snaitf** [comment]
Upon further examination, it's in there several times: WaterBreathing, Dolphin, Sponge, and WaterWalking all say "underwater_run_small" instead of "ruin"

**Comment by focamacho** [comment]
Thanks for pointing that!
