### ISSUE TITLE
Internal Exception: java.lang.IndexOutOfBoundsException issue in multiplayer game (possible issue is curios api)

### ISSUE THREAD

**Issue by MstDominik** [Focamacho/RingsOfAscension#78]
when i equip ring and try take off from curios menu i dissconect from server with this inscription (Internal Exception: java.lang.IndexOutOfBoundsException ) i duplicate this to Curios too

**Comment by focamacho** [comment]
I'm pretty sure it is not an issue with Rings of Ascension. If it is still happening with only Rings of Ascension + Curios installed, let me know!
