### ISSUE TITLE
Mythic Ring Spawning

### ISSUE THREAD

**Issue by lithospace** [Focamacho/RingsOfAscension#79]
Do Mythic Rings Spawn One time only or are they just insanely rare? In 200 end city chests, I've only found one ring of flight.

**Comment by focamacho** [comment]
They are really rare, you can increase the chance of a ring to spawn by increasing the value of `configRingMinLoot` in the config file.

**Comment by mberlin1** [comment]
Ring of Regeneration (rings of ascension)
Running from pack tnp limitless 5, minecraft 1.18.2.
I'm unsure if betterstronghold:stronghold is interfering with its spawn, but at last count I've looked in 76 strongholds, going west from my spawn. I'm at about -80000 by 25000. I've looked in every single stronghold library in each of these strongholds, and have not found this ring. It claims a spawn rate of 25% per stack. I've found all the other rings, but not this one. Any chance Yung's better strongholds is interfering somehow?
Looking through the configs there's nothing that leads me to believe that it is -- it only has configs for a single type of room it adds, a storage room, which as foodstuffs and other things on display.

If the chance listed in the JEI is accurate then something is definitely wrong. (25% of 0-1 stacks, stronghold library)

In reference to the above comment, there is no such config file in the modpack.  No configs listed at all for this mod, in fact.

**Comment by focamacho** [comment]
> Ring of Regeneration (rings of ascension) Running from pack tnp limitless 5, minecraft 1.18.2. I'm unsure if betterstronghold:stronghold is interfering with its spawn, but at last count I've looked in 76 strongholds, going west from my spawn. I'm at about -80000 by 25000. I've looked in every single stronghold library in each of these strongholds, and have not found this ring. It claims a spawn rate of 25% per stack. I've found all the other rings, but not this one. Any chance Yung's better strongholds is interfering somehow? Looking through the configs there's nothing that leads me to believe that it is -- it only has configs for a single type of room it adds, a storage room, which as foodstuffs and other things on display.
> 
> If the chance listed in the JEI is accurate then something is definitely wrong. (25% of 0-1 stacks, stronghold library)
> 
> In reference to the above comment, there is no such config file in the modpack. No configs listed at all for this mod, in fact.

If Better Strongholds uses their own loot tables, so yes, the rings will not be able to gen inside their chests, at least not without adding those loot tables manually to the config file.

The config file can be found at your .minecraft/config/ringsofascension-common.toml
Being ".minecraft" your modpack instance folder.
It requires you to restart minecraft after changing this file.

It seems like TNP Limitless changed the configRingMinLoot from -5 to -10, making the rings even more rare.

**Comment by mberlin1** [comment]
Ah, i was unaware -- i simply searched the string you mentioned in the mod's general config folder. I'll take a look, but thank you very much for the information. When looking at the chests in question, the tags list it as still having the same loot table as "strong hold library" so I'm guessing they merely messed with the loot % not the actual contents.  

Just for reference, the JEI says its 25%, 0-1 stacks.
With a loot chance of -10, what does that actually equate to? (I'm a software engineer, but I'm unsure what's doing the rolling and where -10 ranks as a percent)

using this as a reference: 
https://learn.microsoft.com/en-us/minecraft/creator/documents/lootandtradetablefunctions?source=recommendations  (which is probably for bedrock)  i don't see anywhere the value for weight or chance could be anything other than a positive value.

**Comment by focamacho** [comment]
If the minimum amount of rings to spawn is -10, and the max is 1 (configRingMinLoot and configRingMaxLoot), from 11 chances only one will spawn a ring.
And it is to spawn the ring's pool. The rings will still have their chances between themselves to spawn from the pool.

So 1 to 11 is 9,09% for a ring to spawn.
But inside this pool, there is multiple rings. For `stronghold_library` there is Ring of Regeneration, Ring of Strength and Ring of Health.

Each tier has his own weight:
Common -> 20
Rare -> 15
Epic -> 10
Legendary -> 5
Mythic -> 1

Ring of Strength is an Epic Ring (10)
Ring of Health is a Legendary Ring (5)
Ring of Regeneration is a Legendary Ring (5)

So inside the pool it is 5 to 20 for the ring to spawn (25%)

So if my math is right and we multiply the percentages 9.09% and 25%, it is a 0.022% chance for the ring to spawn.

**Comment by mberlin1** [comment]
Thank you so much for taking the time to make a detailed response, I really appreciate it.
