### ISSUE TITLE
Config not working with modded loot tables [1.18.2]

### ISSUE THREAD

**Issue by arzadu** [Focamacho/RingsOfAscension#81]
Something I've noticed with RoA and structure mods: even after adding rings to modded loot tables via the config, they don't generate in modded loot tables (tested with IDAS and Apotheosis by setting ring chances very high and repeatedly summoning chests with the relevant loot tables). Rings still generate fine in vanilla loot tables, but I figured this was relevant enough to report it. If I'm just being an idiot, feel free to let me know how to fix the idiocy.

Thanks so much for a wonderful mod!

edit: this is on Forge, just to make sure that's in here

**Comment by focamacho** [comment]
For 1.19.4+ I am switching from config options for loot tables to data packs, this sould make it easier to configure. Soon I'll release an update.
