### ISSUE TITLE
Your health does not update immediately if you unequip the `Ring of Max Health`

### ISSUE THREAD

**Issue by SiverDX** [Focamacho/RingsOfAscension#84]
This affects regenerated hearts (empty hearts get removed)
It seems they only update if somethings happens to your health (e. g. you take damage)

Adding something like this in `ItemRingHealth.java` fixes the problem

``` java
@Override
public void onUnequippedCurio(String identifier, LivingEntity livingEntity) {
    if (livingEntity.getHealth() > livingEntity.getMaxHealth()) {
        livingEntity.setHealth(livingEntity.getMaxHealth());
    }
}
```
(Referenced from https://github.com/ochotonida/artifacts/blob/1.19.x/src/main/java/artifacts/item/wearable/belt/CrystalHeartItem.java)

**Comment by focamacho** [comment]
Thank you very much for pointing this out!
