### ISSUE TITLE
[1.20.1] Crash when loading mod on a server.

### ISSUE THREAD

**Issue by Gbergz** [Focamacho/RingsOfAscension#85]
Title ^

MC: 1.20.1
Forge: 47.1.3
ROA: 2.0.0

**Logs**: https://gist.githubusercontent.com/Gbergz/f6e29955dc7ad311c1dc7e6dddde9a59/raw/506045be41993992a2c3a078553e8bdd8b29c809/gistfile1.txt

**Comment by focamacho** [comment]
Thanks for the report! Fixed on the latest version.
CurseForge -> https://legacy.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/4767255
Modrinth -> https://modrinth.com/mod/rings-of-ascension/version/s9CnaavG
