### ISSUE TITLE
Incompatible with Repurposed Sructures

### ISSUE THREAD

**Issue by bons66** [Focamacho/RingsOfAscension#87]
MC 1.20.1 + Fabric loader [0.14.22]
Unable load world. Crash when create New World.

fabric-api-0.89.0+1.20.1.jar
midnightlib-fabric-1.4.1.jar
repurposed_structures-7.1.6+1.20.1-fabric.jar
RingsOfAscension-1.20.1-2.0.1.jar
trinkets-3.7.1.jar

Crash Report
https://pastebin.com/N3L2bcAu

**Comment by TelepathicGrunt** [comment]
Ring of Ascension is force loading loot modifier files that are specific to Forge only.
https://github.com/focamacho/RingsOfAscension/blob/902fbf807c0610907b662beb1a7846050ab62922/src/main/java/com/focamacho/ringsofascension/RingsOfAscension.java#L131

I had the forge json file in common as I would expect said forge json file to simply just do nothing on fabric. You know, cause Forge isn't on fabric lol. So why ring is force loading these loot modifier files on fabric? no idea.

I'll move th file to my forge module so the fabric jar does not get the file anymore but I would strongly recommend for the dev to not force loading arbitrary files that is not expected to be loaded on fabric.

**Comment by TelepathicGrunt** [comment]
v7.1.8 repurposed structures no longer has the forge loot modifier json files so ring of ascension should have nothing to load from my fabric jar anymore. Should fix crash but I can't say if ring of ascension will cause issues with other mods that happen to keep their forge loot modifier file around.

**Comment by focamacho** [comment]
Hello! Sorry for this. I made the mod load the loot_modifier files so I can use the same files for the forge and fabric versions of the mod, but I didn't expect it to try to load other mods modifiers too.
Thanks for addressing the issue on your side even with it being my fault. I'll add an extra check to make sure I'm loading only the modifiers from Rings of Ascension. 😅

**Comment by focamacho** [comment]
Latest version should fix the issue: https://modrinth.com/mod/rings-of-ascension/version/Jz5Uw4YZ
