### ISSUE TITLE
Crash when try to create a new world

### ISSUE THREAD

**Issue by NTalexGHOST** [Focamacho/RingsOfAscension#88]
[To Reproduce]
Just try to create a new world, already created worlds will be considered "damaged"

[Game Environment]
 - Minecraft: 1.20.1
 - Fabric Api: 0.89.3
 - Rings Of Ascension: 2.0.2
 - Trinkets: 3.7.1

[crash-2023-10-05_06.44.04-client.txt](https://github.com/focamacho/RingsOfAscension/files/12812056/crash-2023-10-05_06.44.04-client.txt)

**Comment by focamacho** [comment]
Hello! Should be fixed on the latest version: https://modrinth.com/mod/rings-of-ascension/version/Jz5Uw4YZ
