### ISSUE TITLE
Modify ring amplifiers/duration/hearts?

### ISSUE THREAD

**Issue by AikamiT** [Focamacho/RingsOfAscension#89]
Hello, this is not an issue but a question.

I noticed you added a ringsofascension-common.toml file and I suppose I can use that file to modify values from the different rings.

I modified multiple vlaues and I just can't see a change in my game, am I doing something wrong?

I've changed values such as **ringUndyingCoooldown**, **ringHealthHearts** and **ringAmplifierJumpBoost**.

If it is needed:
The version I'm currently using of Minecraft is 1.20.2 with a forge version 48.1.0

**Comment by Rodrigo816** [comment]
yha same problem.

**Comment by focamacho** [comment]
Thanks for the report! Should be fixed in the latest version
https://legacy.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/5166182
