### ISSUE TITLE
Ring of flight issue [1.15.2][Forge]

### ISSUE THREAD

**Issue by chimericdream** [Focamacho/RingsOfAscension#9]
When I equip the ring of flight, it often takes multiple attempts to enter flight mode. When it fails, the screen stutters as though I'm going into and out of flight mode rapidly, while slowly descending like I would with slow falling. When it works (usually takes 3-4 tries), it "just works" as expected.

Any idea what could be causing this?

**Comment by focamacho** [comment]
v1.5.3 should fix this
Here is: https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/3003529

**Comment by chimericdream** [comment]
Thanks! In my local testing, things seem to be working well. I will be updating our modpack in the next day or so and will be able to test on a server at that point. 🤞

**Comment by chimericdream** [comment]
Sorry for the long delay in responding. Everything seems to be working since updating to the latest version of the mod. Thanks!
