### ISSUE TITLE
ringHealthHearts not taking effect

### ISSUE THREAD

**Issue by Rodrigo816** [Focamacho/RingsOfAscension#90]
In ringsofascension-common.toml I set
	ringHealthHearts = 5

and doesn't take effect on game.

MC: 1.20.1
FORGE: 47.2.20

**Comment by focamacho** [comment]
Thanks for the report! Should be fixed in the latest version
https://legacy.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/5166182
