### ISSUE TITLE
Config does not seem to work.

### ISSUE THREAD

**Issue by Qwitsch** [Focamacho/RingsOfAscension#92]
Changing values in the config file does not seem to affect the game in any way. 
Changing the health, availability, or potion effect intensity does not do anything.

MC 1.20.1 Mod 2.0.1

**Comment by focamacho** [comment]
Thanks for the report! Should be fixed in the latest version
https://legacy.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/5166182
