### ISSUE TITLE
[NeoForge 1.20.4] Mod doesn't load (javafml version dependency too high) + Crash when the dependency issue is fixed (probably loader-specific rendering code)

### ISSUE THREAD

**Issue by Desempregago** [Focamacho/RingsOfAscension#93]
[Crash Report](https://mclo.gs/prcFTN4)

Minecraft 1.20.4
NeoForge 20.4.189
Curios 7.3.1
RoA 2.0.0

**Comment by focamacho** [comment]
Thanks for the report. I have released a new version specific for NeoForge:
CurseForge -> https://curseforge.com/minecraft/mc-mods/rings-of-ascension/files/5172236
Modrinth -> https://modrinth.com/mod/rings-of-ascension/version/YmPAHdQO
